apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: ClusterIP
  selector:
    app: flask-wedding
  ports:
    - port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx-wedding
  ports:
    - name: http
      port: 80
      nodePort: 30007
    - name: https
      port: 443
      nodePort: 30008
