apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: NodePort
  selector:
    app: flask-webapp
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30007

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx-webapp
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30008
