pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                script{
                    echo 'Pipeline is building'
                    dir('flask'){
                        def docker_image = docker.build('kevin:test')

                    }

                }
            }
        }
        stage('Push') {
            steps {
                echo 'Pipeline is pushing'
            }
        }
    }
}