pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo 'Pipeline is building'
            }
        }
        stage('Push') {
            steps {
                echo 'Pipeline is pushing'
            }
        }
    }
}